"""
2_test.py - MLP Test for Gandou 4-class classification
Loads mlp4.pth, tests on gandou_test.csv
If accuracy < 75%, loops through hyperparameter configs and retrains
"""
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import subprocess
import sys
import os

# Set random seeds
torch.manual_seed(42)
np.random.seed(42)


class MLP(nn.Module):
    """3-layer MLP for 4-class classification"""
    def __init__(self, input_size=16, hidden1=64, hidden2=32, num_classes=4, dropout=0.2):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout)
        self.fc2 = nn.Linear(hidden1, hidden2)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout)
        self.fc3 = nn.Linear(hidden2, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.dropout1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.dropout2(x)
        x = self.fc3(x)
        return x


def load_model(model_path='model/mlp4.pth'):
    """Load MLP model and normalization parameters"""
    checkpoint = torch.load(model_path, weights_only=False)
    mean = checkpoint['mean']
    std = checkpoint['std']

    # Try both possible key names for state dict
    if 'model_state_dict' in checkpoint:
        state_dict = checkpoint['model_state_dict']
    elif 'model.state_dict()' in checkpoint:
        state_dict = checkpoint['model.state_dict()']
    else:
        raise KeyError(f"Cannot find model state dict in checkpoint. Keys: {checkpoint.keys()}")

    # Infer hidden layer sizes and model type from state dict
    # Handle both MLP class (fc1.weight) and Sequential (net.0.weight)
    if 'fc1.weight' in state_dict:
        hidden1 = state_dict['fc1.weight'].shape[0]
        hidden2 = state_dict['fc2.weight'].shape[0]
        model = MLP(input_size=16, hidden1=hidden1, hidden2=hidden2, num_classes=4)
    elif 'net.0.weight' in state_dict:
        # Sequential model from existing 2_train.py
        hidden1 = state_dict['net.0.weight'].shape[0]
        hidden2 = state_dict['net.3.weight'].shape[0]
        model = MLP4(input_dim=16)
    else:
        raise KeyError(f"Unknown state dict keys: {list(state_dict.keys())[:5]}")

    model.load_state_dict(state_dict)
    model.eval()

    return model, mean, std


class MLP4(nn.Module):
    """Sequential MLP from original 2_train.py"""
    def __init__(self, input_dim=16):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 4)
        )

    def forward(self, x):
        return self.net(x)


def standardize(X, mean, std):
    """Standardize features using mean and std"""
    return (X - mean) / std


def predict(model, X_std):
    """Make predictions with the model"""
    device = next(model.parameters()).device
    X_tensor = torch.tensor(X_std, dtype=torch.float32).to(device)
    with torch.no_grad():
        outputs = model(X_tensor)
        _, predictions = torch.max(outputs, 1)
    return predictions.cpu().numpy()


def print_class_results(y_true, y_pred, num_classes=4):
    """Print per-class accuracy and sample counts"""
    print("\nPer-class prediction results:")
    print("-" * 50)
    for cls in range(num_classes):
        cls_mask = (y_true == cls)
        cls_count = cls_mask.sum()
        if cls_count > 0:
            cls_correct = ((y_pred == cls) & cls_mask).sum()
            cls_acc = cls_correct / cls_count * 100
            print(f"  Class {cls}: {cls_correct}/{cls_count} correct ({cls_acc:.2f}%)")
        else:
            print(f"  Class {cls}: No samples")


def generate_train_script(hidden1, hidden2, lr, dropout, epochs):
    """Generate 2_train.py with given hyperparameters"""
    train_script = f'''"""
2_train.py - MLP for Gandou 4-class classification
Auto-generated by 2_test.py for hyperparameter tuning
"""
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
import os

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)


class MLP(nn.Module):
    """3-layer MLP for 4-class classification"""
    def __init__(self, input_size=16, hidden1={hidden1}, hidden2={hidden2}, num_classes=4, dropout={dropout}):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden1)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout)
        self.fc2 = nn.Linear(hidden1, hidden2)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout)
        self.fc3 = nn.Linear(hidden2, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.dropout1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.dropout2(x)
        x = self.fc3(x)
        return x


def train_mlp(hidden1={hidden1}, hidden2={hidden2}, lr={lr}, dropout={dropout}, epochs={epochs}, batch_size=32):
    """Train MLP on gandou_train.csv"""
    # Load data
    train_df = pd.read_csv('data/gandou_train.csv')
    X_train = train_df.drop('Class', axis=1).values.astype(np.float32)
    y_train = train_df['Class'].values.astype(np.longlong)

    # Compute mean and std for normalization
    mean = X_train.mean(axis=0)
    std = X_train.std(axis=0)
    std[std == 0] = 1  # Avoid division by zero

    # Normalize
    X_train = (X_train - mean) / std

    # Convert to tensors
    X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train, dtype=torch.longlong)

    # Create DataLoader
    dataset = TensorDataset(X_train_tensor, y_train_tensor)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Initialize model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = MLP(input_size=16, hidden1=hidden1, hidden2=hidden2, num_classes=4, dropout=dropout)
    model = model.to(device)

    # Loss and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)

    # Training loop
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for batch_X, batch_y in dataloader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        if (epoch + 1) % 50 == 0:
            print(f"  Epoch [{{epoch+1}}/{{epochs}}], Loss: {{total_loss/len(dataloader):.4f}}")

    # Save model with consistent key format
    os.makedirs('model', exist_ok=True)
    torch.save({{
        'model.state_dict()': model.state_dict(),
        'mean': mean,
        'std': std
    }}, 'model/mlp4.pth')
    print(f"  Model saved to model/mlp4.pth")

    return model, mean, std


if __name__ == '__main__':
    print("=" * 60)
    print("Training MLP for Gandou 4-class classification")
    print("=" * 60)
    print(f"Config: hidden1={hidden1}, hidden2={hidden2}, lr={lr}, dropout={dropout}, epochs={epochs}")

    print("\\n[Training]")
    model, mean, std = train_mlp(hidden1=hidden1, hidden2=hidden2, lr=lr, dropout=dropout, epochs=epochs)

    print("\\n" + "=" * 60)
    print("Training complete!")
    print("=" * 60)
'''
    with open('2_train.py', 'w', encoding='utf-8') as f:
        f.write(train_script)
    print(f"  Generated new 2_train.py with config: hidden1={hidden1}, hidden2={hidden2}, lr={lr}, dropout={dropout}, epochs={epochs}")


def main():
    print("=" * 60)
    print("MLP 4-class Classification Test")
    print("=" * 60)

    # Hyperparameter configs to try if accuracy < 75%
    configs = [
        {'hidden1': 128, 'hidden2': 64, 'lr': 0.001, 'dropout': 0.3, 'epochs': 300},
        {'hidden1': 64, 'hidden2': 32, 'lr': 0.005, 'dropout': 0.2, 'epochs': 500},
        {'hidden1': 128, 'hidden2': 64, 'lr': 0.0005, 'dropout': 0.3, 'epochs': 400},
        {'hidden1': 256, 'hidden2': 128, 'lr': 0.001, 'dropout': 0.4, 'epochs': 300},
    ]

    # Check if model exists
    model_path = 'model/mlp4.pth'
    if not os.path.exists(model_path):
        print(f"\nModel not found at {model_path}. Running 2_train.py first...")
        result = subprocess.run([sys.executable, '2_train.py'], cwd='.')
        if result.returncode != 0:
            print("ERROR: 2_train.py failed to run")
            return

    # Load model
    print(f"\nLoading model from {model_path}...")
    try:
        model, mean, std = load_model(model_path)
        print("  Model loaded successfully")
    except Exception as e:
        print(f"  Error loading model: {e}")
        print("  Retraining with default config...")
        subprocess.run([sys.executable, '2_train.py'], cwd='.')
        model, mean, std = load_model(model_path)

    device = next(model.parameters()).device
    print(f"  Model device: {device}")

    # Load test data
    print("\nLoading test data...")
    test_df = pd.read_csv('data/gandou_test.csv')
    X_test = test_df.drop('Class', axis=1).values.astype(np.float32)
    y_test = test_df['Class'].values.astype(np.int64)
    print(f"  Test set: {X_test.shape[0]} samples, {X_test.shape[1]} features")

    # Standardize
    X_test_std = standardize(X_test, mean, std)

    # Predict
    print("\nPredicting...")
    y_pred = predict(model, X_test_std)

    # Calculate accuracy
    correct = (y_pred == y_test).sum()
    total = len(y_test)
    accuracy = correct / total * 100

    print("\n" + "=" * 60)
    print("Test Results")
    print("=" * 60)
    print(f"  Test set accuracy: {accuracy:.2f}%")
    print(f"  Correct predictions: {correct}/{total}")

    # Print per-class results
    print_class_results(y_test, y_pred, num_classes=4)

    # Check if accuracy meets threshold
    threshold = 75.0
    if accuracy >= threshold:
        print(f"\n{'[PASS]':^60}")
        print(f"Accuracy {accuracy:.2f}% >= {threshold}% - Target achieved!")
        return

    print(f"\nAccuracy {accuracy:.2f}% < {threshold}%")
    print("Starting hyperparameter search...")

    # Loop through configs
    for i, config in enumerate(configs):
        print(f"\n--- Config {i+1}/{len(configs)}: {config} ---")

        # Generate new training script
        generate_train_script(**config)

        # Run training
        print("  Running 2_train.py...")
        result = subprocess.run([sys.executable, '2_train.py'], cwd='.')
        if result.returncode != 0:
            print(f"  ERROR: 2_train.py failed with return code {result.returncode}")
            continue

        # Reload model
        try:
            model, mean, std = load_model(model_path)
            X_test_std = standardize(X_test, mean, std)
            y_pred = predict(model, X_test_std)
            correct = (y_pred == y_test).sum()
            accuracy = correct / total * 100

            print(f"\n  Config {i+1} accuracy: {accuracy:.2f}%")
            print_class_results(y_test, y_pred, num_classes=4)

            if accuracy >= threshold:
                print(f"\n{'[PASS]':^60}")
                print(f"Accuracy {accuracy:.2f}% >= {threshold}% - Target achieved!")
                return

        except Exception as e:
            print(f"  Error during re-evaluation: {e}")
            continue

    # All configs exhausted
    print("\n" + "=" * 60)
    print(f"{'[FAIL]':^60}")
    print(f"Accuracy {accuracy:.2f}% < {threshold}% after all configurations")
    print("=" * 60)


if __name__ == '__main__':
    main()